# base URL
baseURL = 'https://visionbike.github.io'
# site publish directory
publishdir = "visionbike.github.io"
# language code
languageCode = 'en-us'
# site title
title = 'Visionbike'
# site theme
theme = "LoveIt"

# site author config
[author]
    name = "Phuc Thanh-Thien Nguyen"
    email = "phuc.visionbike@gmail.com"

# site header config
[params.header]
    # desktop header mode ["fixed", "normal", "auto"]
    desktopMode = "auto"
    # mobile header mode ["fixed", "normal", "auto"]
    mobileMode = "auto"
    # header title config
    [params.header.title]
        # logo URL
        logo = ""
        # title name
        name = "Visionbike"
        # whether to use typeit aniomation
        typeit = false

# site footer config
[params.footer]
    enable = true
    # whether to show Hugo and theme info
    hugo = true
    # whether to show copyright info
    copyright = true
    # whether to show author
    author = true
    # site creation time
    since = 2023

# site app config
[params.app]
    # optional site title override for the app when added to an iOS home screen or Android launcher
    title = "visionbike.github.io"
    # whether to omit favicon resource links
    noFavicon = false
    # modern SVG favicon to use in place of older style .png and .ico files
    svgFavicon = "/images/favicon.svg"

# home page config
[params.home]
    # home page profile
    [params.home.profile]
        enable = true
        # avatar URL shown in home page
        avatarURL = "/images/avatar-3d.png"
        # title shown in the home page
        title = "visionbike.github.io"
        # subtitle shown in the home page
        subtitle = "Personal Notes for CV | DSP | ML"
        # disclaimer
        disclaimer = ""
        # whether to show social links
        social = true
        # whether to use typeit animation for subtitle
        typeit = true

# social config in home page
[params.social]
    [params.social.GitHub]
        weight = 1
        id = "visionbike"
        title = "Github"
    [params.social.Linkedin]
        weight = 2
        id = "nttphuc"
        title = "Linkedin"
    [params.social.Email]
        # weight when arranging icons (the greater the weight, the later the icon is positioned) 
        weight = 3
        # social ID
        id = "phuc.visionbike@gmail.com"
        # content honvering on the icon
        title = "Email"

# page global config
[params.page]
    # table of content config
    [params.page.toc]
        # whether to enable table of the contents
        enable = true
        # whether to keep the table of the contents in front of the post
        keepStatic = true
        # whether to make the table of the contents the sidebar automatically collapse
        auto = true

# menu config
[menu]
    [[menu.main]]
        weight = 1
        identifier = "posts"
        name = "Posts"
        url = "/posts/"
    [[menu.main]]
        weight = 2
        identifier = "tags"
        name = "Tags"
        url = "/tags/"
    [[menu.main]]
        weight = 3
        identifier = "categories"
        name = "Categories"
        url = "/categories/"
    [[menu.main]]
        weight = 4
        identifier = "about"
        name = "About"
        url = "/about/"
    [[menu.main]]
        weight = 5
        identifier = "cv"
        name = "CV"
        url = "/cv/"

# markup related config in Hugo
[markup]
    # syntax highlighting (https://gohugo.io/content-management/syntax-highlighting)
    [markup.highlighting]
        codeFences = true
        guessSyntax = true
        lineNos = true
        lineNumbersInTable = true
        # false is a necessary configuration (https://github.com/dillonzq/LoveIt/issues/158)
        noClasses = false
    # Goldmark is from Hugo 0.60 the default labrary used for markdown
    [markup.goldmark]
        [markup.goldmark.extensions]
            definitionList = true
            footnote = true
            linkify = true
            strikethrough = true
            table = true
            taskList = true
            typographer = true
        [markup.goldmark.renderer]
            # whether to use HTML tags directly in the document
            unsafe = true
    # table of contents settings
    [markup.tableOfcontents]
        startLevel = 2
        endLevel = 6

# sitemap config
[sitemap]
    changefreq = "monthly"
    filename = "sitemape.xml"
    priority = 0.5


# permalinks config
[permalinks]
    posts = ":filename"
